#!/bin/bash

misc() {
	# Optimizations
	nc=$(grep -c ^processor /proc/cpuinfo)
	TOTAL_MEM=$(cat /proc/meminfo | grep -i 'memtotal' | grep -o '[[:digit:]]*')
	if [[ $TOTAL_MEM -gt 8000000 ]]; then
		sed -i "s/#MAKEFLAGS=\"-j2\"/MAKEFLAGS=\"-j$nc\"/g" /etc/makepkg.conf
		sed -i "s/COMPRESSXZ=(xz -c -z -)/COMPRESSXZ=(xz -c -T $nc -z -)/g" /etc/makepkg.conf
	fi

	# Setup locale
	echo "en_US.UTF-8 UTF-8" >>/etc/locale.gen
	locale-gen
	echo "LANG=en_US.UTF-8" >/etc/locale.conf

	# Setup time and date
	ln -sf /usr/share/zoneinfo/Asia/Manila /etc/localtime
	hwclock --systohc

	# enable nm
	tee /etc/NetworkManager/conf.d/10_nodns.conf > /dev/null <<-EOF
		[main]
		dns=none
	EOF
	systemctl enable NetworkManager

	# Add crypttab
	uuid="7d2df54f-60df-410c-b5a1-d867a7d4f0c9"
	if blkid | grep $uuid > /dev/null; then
		tee -a /etc/crypttab > /dev/null <<-EOF
			aj-drive UUID=${uuid} /root/keyfile nofail
		EOF
	fi

	# Add Swapfile
	btrfs subvolume create /swap
	btrfs filesystem mkswapfile --size 50g --uuid clear /swap/swapfile
	if [ $? -eq 0 ]; then
		tee -a /etc/fstab > /dev/null <<-EOF
			#Swap
			/swap/swapfile none swap defaults 0 0
		EOF
	fi

	echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
	sysctl -p
}

setup_ajdisk() {
	mkdir /mnt/AJ
	chown 1000:1000 /mnt/AJ
	tee -a /etc/fstab > /dev/null <<-EOF
		# AJ
		/dev/mapper/aj-drive /mnt/AJ ext4 defaults,noatime,nodiratime 0 2
	EOF
}

main() {
	setup_ajdisk
	misc
}

if [[ "$*" != *"--source"* ]]; then
	main "$@"
fi
