#!/bin/bash

# Install yay
cwd=$(pwd)
git clone https://aur.archlinux.org/yay /tmp/yay
cd /tmp/yay
makepkg -si --noconfirm
cd "$cwd"
rm -rf /tmp/yay

# Instll plymouth
yay -S plymouth
yay -S plymouth-theme-colorful-loop-git --noconfirm

sed -i '/^HOOKS/s/udev/& plymouth/' /etc/mkinitcpio.conf

sudo plymouth-set-default-theme -R colorful_loop
