#!/bin/bash

nc=$(grep -c ^processor /proc/cpuinfo)
TOTAL_MEM=$(cat /proc/meminfo | grep -i 'memtotal' | grep -o '[[:digit:]]*')
if [[ $TOTAL_MEM -gt 8000000 ]]; then
    sed -i "s/#MAKEFLAGS=\"-j2\"/MAKEFLAGS=\"-j$nc\"/g" /etc/makepkg.conf
    sed -i "s/COMPRESSXZ=(xz -c -z -)/COMPRESSXZ=(xz -c -T $nc -z -)/g" /etc/makepkg.conf
fi

# Setup locale
echo "en_US.UTF-8 UTF-8" >>/etc/locale.gen
locale-gen
echo "LANG=en_US.UTF-8" >/etc/locale.conf

# Setup time and date
ln -sf /usr/share/zoneinfo/Asia/Manila /etc/localtime
hwclock --systohc

systemctl enable NetworkManager

cat <<EOF >>/etc/crypttab
aj-drive UUID=055372e2-c647-4e7c-acf4-2fb5ad83f338 /root/keyfile nofail
EOF

# Install plymouth theme
# curl -o /tmp/plymouth-archlinux.zip https://install.alvinjay.site/plymouth-archlinux.zip
# unzip -x /tmp/plymouth-archlinux.zip -d /usr/share/plymouth/themes
