#!/bin/bash

execute_command() {
    while true; do
        "$@"
        exit_code=$?
        if [ $exit_code -eq 0 ]; then
            break
        else
            echo "Command failed with exit code $exit_code."
            choice=$(gum choose "Continue the script" "Retry the command" "Exit the script")
            case $choice in
            "Continue the script") break ;;
            "Retry the command") continue ;;
            "Exit the script") exit 1 ;;
            esac
        fi
    done
}

set -e

# Ensure /mnt is unmounted
if lsblk | grep "/mnt$" >/dev/null 2>&1; then
    umount -q -A --recursive /mnt
fi

# Print available disks
lsblk -n --output TYPE,KNAME,SIZE | awk '$1=="disk"{print $2"|"$3}'

# Enter necessary infos
read -r -p "Enter disk name: " disk
read -r -p "Enter username: " username
read -r -p "Enter Full Name: " fullname
read -r -p "Enter computer name: " hostname

while :; do
    read -s -r -p "Enter user password: " password
    echo
    read -s -r -p "Enter user password again: " password2
    echo
    [[ $password != "$password2" ]] || break
    echo "error try again"
done

while :; do
    echo
    read -s -r -p "Enter root password: " rootPassword
    echo
    read -s -r -p "Enter root password: " rootPassword2
    echo
    [[ $rootPassword != "$rootPassword2" ]] || break
    echo "error try again"
done

while :; do
    echo
    read -s -r -p "Enter luks password: " luksPassword
    echo
    read -s -r -p "Enter luks password: " luksPassword2
    echo
    [[ $luksPassword != "$luksPassword2" ]] || break
    echo "error try again"
done

clear

## Setup pacman config
sed -i 's/^#ParallelDownloads/ParallelDownloads/' /etc/pacman.conf
sed -i 's/^#Color/Color/' /etc/pacman.conf

## Configure Mirrors
echo "Updating mirrors using reflector"
reflector -a 48 -c JP -f 5 -l 20 --sort rate --save /etc/pacman.d/mirrorlist

## Setup pacman
pacman-key --init
pacman-key --populate

pacman -Sy archlinux-keyring --noconfirm

pacman -S gum --noconfirm

## Setup disk
device=/dev/${disk}
wipefs --all "${device}"
sgdisk --clear "${device}" --new 1::-512MiB "${device}" --new 2::0 --typecode 2:ef00 "${device}"
sgdisk --change-name=1:primary --change-name=2:ESP "${device}"

if [[ $disk == *"nvme"* ]]; then
    part_root=${device}p1
    part_boot=${device}p2
else
    part_root=${device}1
    part_boot=${device}2
fi

mkfs.vfat -n "EFI" -F 32 "${part_boot}"

## Setuo LUKS
echo -n "${luksPassword}" | cryptsetup luksFormat "${part_root}"
echo -n "${luksPassword}" | cryptsetup luksOpen "${part_root}" root
part_root_install=/dev/mapper/root

mkfs.btrfs -fL btrfs ${part_root_install}
mount ${part_root_install} /mnt

btrfs subvolume create /mnt/@
btrfs subvolume create /mnt/@var
btrfs subvolume create /mnt/@home
btrfs subvolume create /mnt/@snapshots

umount /mnt
mount -m -o noatime,nodiratime,compress=zstd,subvol=@ ${part_root_install} /mnt
mount -m -o noatime,nodiratime,compress=zstd,subvol=@var ${part_root_install} /mnt/var
mount -m -o noatime,nodiratime,compress=zstd,subvol=@home ${part_root_install} /mnt/home
mount -m -o noatime,nodiratime,compress=zstd,subvol=@snapshots ${part_root_install} /mnt/.snapshots

mount -m "$part_boot" /mnt/boot

pacstrap /mnt btrfs-progs
# mount ${part_boot} /mnt/boot --mkdir

# Determine intel or amd
ucode=""
if lscpu | grep "Model name:" | grep AMD >/dev/null 2>&1; then
    ucode="amd-ucode"
elif lscpu | grep "Model name:" | grep Intel >/dev/null 2>&1; then
    ucode="intel-ucode"
else
    echo "Unkown CPU"
    exit 1
fi

## Install Arch
execute_command pacstrap /mnt iptables-nft mkinitcpio
execute_command pacstrap /mnt base linux-zen linux-zen-headers linux-firmware $ucode base-devel
execute_command pacstrap /mnt git vim sudo efibootmgr networkmanager pacman-contrib
execute_command pacstrap /mnt wireplumber pipewire-audio pipewire-pulse pipewire-jack pipewire-alsa gst-plugin-pipewire

# remove fallback from mkinitcpio
sed -i "s/'default' 'fallback'/'default'/" /mnt/etc/mkinitcpio.d/linux-*.preset

## Setup fstab
genfstab -U /mnt >>/mnt/etc/fstab

## Copy post install to new root
cp /etc/pacman.conf /mnt/etc/pacman.conf -f

## Setup users and password
useradd -m -R /mnt "$username"
usermod -R /mnt -c "$fullname" "$username"
usermod -R /mnt -aG wheel "$username"
echo -n "${username}:${password}" | chpasswd -R /mnt
echo -n "root:${rootPassword}" | chpasswd -R /mnt

# Temporarily setup user as sudo nopasswd
echo "${username} ALL=(ALL) NOPASSWD: ALL" >/mnt/etc/sudoers.d/00_"${username}"

# Setup Systemd-boot
arch-chroot /mnt bootctl install

cat <<EOF >/mnt/boot/loader/loader.conf
default  arch.conf
timeout  0
console-mode max
editor   no
EOF

device_uuid=$(blkid | grep "${part_root}" | grep -oP ' UUID="\K[\w\d-]+')

cat <<EOF >/mnt/boot/loader/entries/arch.conf
title   Arch Linux
linux   /vmlinuz-linux-zen
initrd  /initramfs-linux-zen.img
options cryptdevice=UUID=$device_uuid:root root=/dev/mapper/root rootfstype=btrfs rootflags=subvol=@ quiet splash rw
EOF

# Setup mkinitcpio
sed -i '/^HOOKS/s/block/& encrypt/' /mnt/etc/mkinitcpio.conf
arch-chroot /mnt mkinitcpio -P

# Proceed to setup
arch-chroot /mnt bash <(curl -s https://arch-install.pages.dev/cachyos/setup)

# Remove nopasswd
sed -i 's/NOPASSWD: //' /mnt/etc/sudoers.d/00_"$username"

# Set hostname
echo "$hostname" >/mnt/etc/hostname
